# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:5173'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started
        deploy:
            resources:
                limits:
                    memory: 2G
                    cpus: '1.0'
                reservations:
                    memory: 512M
                    cpus: '0.25'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        read_only: false
        tmpfs:
            - /tmp
            - /var/tmp
            # - selenium
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
    #     depends_on:
    #         - laravel.test
    mysql:
        image: 'mysql:8.2'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            # Security: Disable dangerous functions
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '0.5'
                reservations:
                    memory: 256M
                    cpus: '0.1'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        command: >
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --innodb-buffer-pool-size=256M
            --max-connections=100
            --log-error-verbosity=2
    redis:
        image: 'redis:7-alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        deploy:
            resources:
                limits:
                    memory: 256M
                    cpus: '0.25'
                reservations:
                    memory: 64M
                    cpus: '0.05'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        command: >
            redis-server
            --appendonly yes
            --appendfsync everysec
            --maxmemory 200mb
            --maxmemory-policy allkeys-lru
            --tcp-keepalive 60
            --timeout 300
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
