targets:
  $default:
    builders:
      hive_generator:
        generate_for:
          exclude:
            - test/**
      json_serializable:
        generate_for:
          exclude:
            - test/**